from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('public_view_selected_category/<int:pk>/',
         views.public_view_selected_category, name="public_view_selected_category"),
    path('public_search_product/', views.public_search_product,
         name='public_search_product'),
    path('public_view_selected_category/public_view_product_details/<int:pk>/',
         views.public_view_product_details, name="public_view_product_details"),
    path('login/', views.login_request, name='login'),
    path('forgot_password/', views.forgot_password, name="forgot_password"),
    path('home/', views.home, name="home"),
    path('categories/', views.category_page, name="category_page"),
    path('categories/delete_cat_id/',
         views.delete_category, name='delete_category'),
    path('categories/check_category/',
         views.check_category, name='check_category'),
    path('categories/upd_category/<int:pk>/',
         views.upd_category, name='upd_category'),
    path('products/', views.product_page, name="product_page"),
    path('product/delete_id/', views.delete_data, name='delete_data'),
    path('product/upd_product/<int:pk>/',
         views.upd_product, name='upd_product'),
    path('product/upd_product/delete_product_img/',
         views.delete_product_img, name='delete_product_img'),
    path('add_new_category/', views.add_new_category, name='add_new_category'),
    path('add_product/', views.add_product, name="add_product"),
    path('userhome/', views.user_home, name="user_home"),
    path('userhome/category_products/<int:pk>/',
         views.view_selected_products, name="view_selected_products"),
    path('userhome/category_products/user_view_product_details/<int:pk>/',
         views.user_view_product_details, name="user_view_product_details"),
    path('offers/', views.offers, name='offers'),
    path('add_offers/', views.add_offers, name='add_offers'),
    path('offers/delete_offers/', views.delete_offers, name='delete_offers'),
    path('user_details/', views.user_details, name='user_details'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('logout', views.logout_request, name='logout'),
    path('userhome/autocomplete/', views.autocomplete_fn, name='autocomplete_fn'),
    path('user_search_product/', views.user_search_product,
         name='user_search_product'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart_view/', views.cart_view, name='cart_view'),
    path('delete_cart/', views.delete_cart, name='delete_cart'),
    path('increment_cart/', views.increment_cart, name='increment_cart'),
    path('decrement_cart/', views.decrement_cart, name='decrement_cart'),
    path('user_home/admin_view_user_order/<int:pk>/',
         views.admin_view_user_order, name='admin_view_user_order'),
    path('user_myorder/', views.user_myorder, name='user_myorder'),
    path('order_history/', views.order_history, name="order_history"),
    path('user_test_details/', views.user_test_details, name='user_test_details'),
    path('edit_user_profile/', views.edit_user_profile, name='edit_user_profile'),
    path('user_reset_password/', views.user_reset_password,
         name='user_reset_password'),
    path('user_delete_session/', views.user_delete_session,
         name='user_delete_session'),
    path('user_signup/', views.user_signup, name='user_signup'),
    path('order_counter/', views.order_counter, name="order_counter"),
    path('find_cart_count/', views.find_cart_count, name="find_cart_count"),
] 


 