# Generated by Django 4.0.2 on 2022-03-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='User_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arman.userdetails'),
        ),
        migrations.AlterField(
            model_name='my_order',
            name='User_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arman.userdetails'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='Product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arman.product'),
        ),
    ]
