# Generated by Django 4.0.2 on 2022-03-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arman', '0002_alter_cart_user_id_alter_my_order_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='User_id',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='my_order',
            old_name='User_id',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='product_images',
            old_name='Product_id',
            new_name='Product',
        ),
    ]
